### ISSUE TITLE
Create a lifecycle manager for CrateKube components

### ISSUE THREAD

**Issue by pdgrenon** [cratekube/cratekube#10]
### Problem to solve
Currently, all CrateKube components must be manually managed by the people operating the platform. This would require each operator to deploy and check for updates from CrateKube repositories, download the update, and then redeploy the component. This requires every operator to have in-depth knowledge of the platform and how these upgrades are performed. 

### Proposal
To reduce the burden of knowledge on operators and to further automate the operational management of the platform, component deployments and upgrades should be automated. 
With automated upgrades, users only need to make a decision for _when_, and do not need knowledge of _how_ to upgrade. This lifecycle management component should:
- Be created as an independent component
- Be responsible for the lifecycle (Create, upgrade, delete) of all deployed CrateKube components
- Be able to upgrade itself
- Make upgrades automated, but not automatic (components should not be upgraded without user's knowledge)

It may be possible to make automatic component upgrades an opt-in feature, but this should be decided as part of the architecture and design discussions. 

### Intended users
This is a core component that would be used primarily by people who adopt the CrateKube platform as a whole. 

### Further details
This has an additional benefit to the CrateKube maintainers by allowing us to deliver future features without requiring users to redeploy the platform. This point is crucial, and one of the reasons this component is included in the MVP. 

### Permissions and Security
This component will require the ability to upgrade all of the other components in the system and itself. This will require a a high level of permissions, and keeping this access isolated should part of both architecture and design discussions. 

### How can we measure success?
No metrics to measure success are recommended at this time, as we do not yet have a baseline MVP to measure against. 

### When is this feature complete?
This issue is complete when the following items have been completed for this component:

- [x] Architecture documentation has been created
- [x] A new repository exists for the code
- [x] A code-level design exists in the new repository
- [x] A new issue to create the tests and implementation has been created in the new repository

### Links / references
This is one of the components for the CrateKube MVP: https://github.com/cratekube/cratekube/blob/master/docs/Architecture.md#lifecycleservice

**Comment by danielfoglio** [comment]
I think we need to discuss and possibly add some verbiage to this issue about how this service is to be the primary initiator of all platform services.

**Comment by pdgrenon** [comment]
Good call. I see that was originally part of the plan in the architecture. I will update the issue to include the requirements for lifecycle management instead of just upgrade management 👍

**Comment by danielfoglio** [comment]
Need to update this issue to reflect decisions made about the user facing documentation being completed in the testing and implementation story.

**Comment by danielfoglio** [comment]
Location of new service: https://github.com/cratekube/lifecycle-service
