### ISSUE TITLE
Document community values

### ISSUE THREAD

**Issue by pdgrenon** [cratekube/cratekube#21]
### Problem to solve
As a team, we consider many values to be important such as respecting each other, caring more about the right answer than being right, transparency, and open discussion. None of these are documented, and as a result it would be difficult to explain the implicit expectations of the CrateKube community to new people that join the project. 

### Proposal
We should document the values we want to see to turn our implicit expectations into explicit expectations. Documentation of the behaviors we to foster in the the community will help us create a culture that both respectful and productive. 

Part of this effort will be a discussion among the current maintainers regarding the culture we want to have in the community.

### Intended users
All community members will need to abide by the values defined in this issue.

### Further details
None.

### Permissions and Security
This document will be completely open to the public. Anyone should be able to see our values!

### Documentation
The primary output of this story is documentation, and no further documentation is needed.

### How can we measure success?
No metrics for success are recommended for this story. 

### When is this feature complete?
This feature is complete when the CrateKube project has defined values for the community that are publicly accessible.

### Links / references
None.

**Comment by forktheweb** [comment]
This passed QA
