### ISSUE TITLE
Document architecture standards

### ISSUE THREAD

**Issue by pdgrenon** [cratekube/cratekube#4]
### Problem to solve
New contributors and developers unfamiliar with our architecture standards have no way to know what is expected for a CrateKube architecture. We have many preferences and implicit expectation regarding architecture, so we should document these expectations to make them explicit.

### Proposal
To help with consistency and to provide clear expectations, the CrateKube architecture standards should be documented. This will need to include at least:
- An explanation of the purpose for CrateKube architecture pages 
- Documentation format (sections, content, questions answered, etc.)
- Included diagrams and their purpose
- Diagram format
- The architecture discussion and approval process

The standards should include relevant examples and a template to make the standards easy to follow. 

### Intended users
All users who plan to architect a new feature for CrateKube. 

### Further details
None.

### Permissions and Security
There are no security implications regarding this documentation. All of this information can be made public, as none of this information should be secret. 

### Documentation
Documentation is the primary deliverable of this issue. There is no need for additional documentation.

### How can we measure success?
The measure of success will be whether or not future architectures follow our documented standards. 

### When is this feature complete?
This feature is complete when all tribal knowledge of CrateKube architecture standards has been documented in a place accessible to the entire CrateKube community. 

### Links / references
Parts of these standards (such as the available security protocols) have been documented in an internal Cisco Confluence page. Those pages will need to be migrated as part of this effort.

**Comment by forktheweb** [comment]
See:  https://github.com/cratekube/cratekube/blob/master/contributing/Architecture%20Guidelines.md
