### ISSUE TITLE
Contribution guidlines should specify issue references in Git commits

### ISSUE THREAD

**Issue by code4dc** [cratekube/cratekube#49]
### Problem to solve
Our commits and PRs should link back to the original issue they are resolving

### Proposal
The Contribution Guidelines document should specify that each commit begin with [cratekube/_<repo_name>#<issue_number>_] and the same reference should be added as a comment to the PR. 

### Intended users
Developers

### Further details
Adding an issue reference to both the commit and the PR will display each commit and PR in the history of the issue. This will make it easier to track the changes performed for each issue. 
We should check if there is a way to automatically include a PR into the issue history based on the commit message w/o having to do it manually. 

### Permissions and Security
N/A
### Documentation
N/A

### How can we measure success?
Our issues have complete history tracking for each commit made in order to resolve the issue. 

### When is this feature complete?
Our Contribution guidelines clearly state where and how an issue reference should be added and our contributors are aware of this step. 

### Links / references
https://github.com/cratekube/cratekube/blob/master/CONTRIBUTING.md

**Comment by pdgrenon** [comment]
I think we should use the "cratekube/<repo>/<issue_number>" syntax in this issue to be more clear. Just having "cratekube/<issue_number>" may not resolve if you are submitting a PR against a different repository than "cratekube."

**Comment by code4dc** [comment]
Very weird, I had <repo> in there but it wasn't showing up until I changed it to <repo_name>

**Comment by pdgrenon** [comment]
Ah, gotcha. "repo" must be a keyword in GitHub. I can't find a reference to what it would do in a comment, but there is documentation here for what that keyword would do in a search: https://help.github.com/en/github/searching-for-information-on-github/searching-for-repositories#search-by-repository-name-description-or-contents-of-the-readme-file
