### ISSUE TITLE
Design an operations management service

### ISSUE THREAD

**Issue by pdgrenon** [cratekube/cratekube#55]
### Problem to solve
CrateKube's one-click cloud provisioning only covers the operations cluster. Without an end-to-end solution, the customer would need to:
1. Use CrateKube automation to spin up the management cluster
2. Manually execute API calls to the cloud management service to create AWS hardware
3. Manually execute API calls to the cluster management service to create a Kubernetes cluster

Because steps 2 and 3 are manual, the customer needs to have knowledge of our system to reach the end goal of using a Kubernetes cluster. 

### Proposal
We should design a new service that ties together the different management services and allows us to automate the full end-to-end experience for our users. This service can become the basis for simplifying operations for our users in the future and is a stepping stone towards eventually providing a UI. 

This service will have two primary responsibilities:
- Bootstrap the initial customer cluster during initial provisioning 
- Tie together management services to simplify operations

During the initial provisioning, this service will need to ensure that steps 2 and 3 in the problem statement are automated. This will provide the full "turn-key" Kubernetes provisioning. 

After initial provisioning, this should be the primary service that users interact with to make changes to the system. For example: A call to this service to "Create a new cluster" may result in a call to cloud management to create new hosts, followed by a call to cluster management to create a new cluster out of the newly provisioned host. 

As part of this issue, we will need to: 
- [x] Create a new repository for this service
- [x] Create an architecture proposal to explain the functionality of this service
- [x] Create a requirements document to think through and document the requirements of this service
- [x] Create a code-level design to lay out the interfaces and resources for this service

### Intended users
This service will be a core component of the CrateKube system. It will be used by all users who adopt the full platform, and will provide the primary interaction point for users. 

### Further details
None. 

### Permissions and Security
As with all management services, we need to ensure that we do not expose any secrets or internal data. Additionally, we will need authentication/authorization around this service to ensure that users are permitted to execute potentially harmful/costly operations such as:
- Creating new AWS hosts
- Deleting existing clusters

### Documentation
This service will need a README for now. Eventually, this service will need documentation in the CrateKube user docs. 

### How can we measure success?
N/A

### When is this feature complete?
This feature is complete when an architectural and code-level design exist for this service. The service tests and implementation will be created as an issue in the repository that is generated for this design. 

### Links / references
None.

**Comment by danielfoglio** [comment]
@pdgrenon Could you expand on what is intended by `Bootstrap the initial customer cluster during initial provisioning`?

**Comment by pdgrenon** [comment]
@danielfoglio Absolutely! We are going for turnkey provisioning of a cluster, then hitting the AWS marketplace entry should not only stand up the management services and management cluster. It will need to stand up the customer cluster as well, so that there isn't any manual action required by the user to start using Kubernetes. 

Since this would know how to talk to all of the other management services, it seems as if it woud have to play a role in the initial bootstrapping of the customer cluster (as opposed to the management cluster, which should already exist by the time this service is available). I was suggesting that this service be responsible for the initial provisioning. Does that help clarify the suggestion?
