### ISSUE TITLE
Define roles and responsibilities for the CrateKube project

### ISSUE THREAD

**Issue by pdgrenon** [cratekube/cratekube#6]
### Problem to solve
Without clear expectations for various roles the CrateKube project, it will be impossible to hold ourselves to high standards. Until roles and responsibilities are defined, there is nothing to measure success or failure against. 

### Proposal
The initial set of roles and responsibilities for CrateKube will be set up by the Cisco team driving the project. As the community grows, we may need to revisit the definitions of existing roles or add more roles.

At least the following roles are suggested as a starting point:
- Maintainer
- Contributor
- Community member
- Management

There may be more roles to define. All roles and responsibilities should be defined with input from all current CrateKube project members. Part of the discussion should consider how these roles can be used to control access and permissions for CrateKube repositories. 

### Intended users
This work will be relevant to all users of the various CrateKube projects. 

### Further details
None.

### Permissions and Security
There are no security implications in publishing this documentation. All of this information can be made public, as none of this information should be secret.

### Documentation
Documentation is the primary deliverable of this issue. There is no need for additional documentation.

### How can we measure success?
Success will be difficult to measure for the documentation portion of this effort. Metrics for how well we are adhering to the defined roles and responsibilities will come at a later date. 

### When is this feature complete?
This feature is complete when all CrateKube project members have clear expectations defined for their individual roles, and a set of expectations exists for external contributors/community members. 

### Links / references
None.

**Comment by code4dc** [comment]
QA Passed
